name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install python requirements
        run: pip install -r requirements.txt
      - name: Install ape plugin requirements
        run: ape plugins install .
      - name: Run tests
        run: ape test
